# Generated by Django 6.0.4 on 2026-08-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_category_contact_emaillog_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscriber',
            name='is_active',
        ),
    ]
