# Generated by Django 6.0.7 on 2026-07-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Dark Chocolate', 'Dark Chocolate'), ('Milk Chocolate', 'Milk Chocolate'), ('Truffle', 'Truffle'), ('Gift Box', 'Gift Box')], max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
